/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketing.system;

/**
 *
 * @author Conor
 */
public class Wireframe2Passenger extends javax.swing.JFrame {

    /**
     * Creates new form Wireframe2Passenger
     */
    public Wireframe2Passenger() {
        initComponents();
        jLabelLine1.setText("Please Scan Your Digital Ticket");
        jLabelLine2.setText("Line ticket bar code up with camera to scan, or alternativly hold digital ticket near device");
        jLabelLine3.setText("1");
        jLabelLine4.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLine1 = new javax.swing.JLabel();
        jLabelLine2 = new javax.swing.JLabel();
        jLabelLine3 = new javax.swing.JLabel();
        jLabelLine4 = new javax.swing.JLabel();

        jLabelLine1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelLine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLine1.setText("jLabel1");

        jLabelLine2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabelLine2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLine2.setText("jLabel1");
        jLabelLine2.setAutoscrolls(true);

        jLabelLine3.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelLine3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLine3.setText("jLabel1");

        jLabelLine4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLine4.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLine1)
                .addGap(18, 18, 18)
                .addComponent(jLabelLine2, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLine3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jLabelLine4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeLine1(String text) {
        jLabelLine1.setText(text);
    }

    public void changeLine2(String text) {
        jLabelLine2.setText(text);
    }

    public void changeLine3(String text) {
        jLabelLine3.setText(text);
    }

    public void changeLine4(String text) {
        jLabelLine4.setText(text);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wireframe2Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wireframe2Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wireframe2Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wireframe2Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wireframe2Passenger().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLine1;
    private javax.swing.JLabel jLabelLine2;
    private javax.swing.JLabel jLabelLine3;
    private javax.swing.JLabel jLabelLine4;
    // End of variables declaration//GEN-END:variables
}
